obj-y		+= access.o bus.o probe.o host-bridge.o \
				   remove.o pci.o pci-driver.o search.o \
				   pci-sysfs.o rom.o setup-res.o irq.o vpd.o \
				   setup-bus.o vc.o mmap.o setup-irq.o

obj-y		+= msi/
obj-y		+= pcie/

obj-y += proc.o
obj-y += slot.o

obj-y	+= quirks.o
obj-y		+= pci-label.o
obj-y		+= vgaarb.o
