KCOV_INSTRUMENT		:= n

obj-y += mutex.o semaphore.o rwsem.o percpu-rwsem.o

KCSAN_SANITIZE_lockdep.o := n

obj-y += spinlock.o
obj-y += osq_lock.o
obj-y += qspinlock.o
obj-y += rtmutex_api.o
obj-y += qrwlock.o
