obj-y	:= br.o br_device.o br_fdb.o br_forward.o br_if.o br_input.o \
			br_ioctl.o br_stp.o br_stp_bpdu.o \
			br_stp_if.o br_stp_timer.o br_netlink.o \
			br_netlink_tunnel.o br_arp_nd_proxy.o br_sysfs_if.o br_sysfs_br.o
