obj-y		+= tty_io.o n_tty.o tty_ioctl.o tty_ldisc.o \
				   tty_buffer.o tty_port.o tty_mutex.o \
				   tty_ldsem.o tty_baudrate.o tty_jobctrl.o \
				   n_null.o
obj-y	+= pty.o
obj-y				+= vt/
obj-y	+= hvc/
obj-y				+= serial/
