#!/bin/bash

remote_build ()
{
	ip=$1

	rsync --delete --exclude=".git" --exclude="G*" -a . $ip::linux 2> /dev/null
	ssh $ip "cd /dev/shm/linux; make CC=/usr/bin/gcc -j$2 "${@:3}" && find build -name "*.o" -o -name "*.d" | cpio -o > $ip.cpio 2> /dev/null"
	rsync $ip::linux/$ip.cpio . 2> /dev/null
	cpio -id < $ip.cpio 2> /dev/null
	rm $ip.cpio
}

make clean

remote_build 192.168.1.2 12 fs mm drivers &
pid[0]=$!

remote_build 192.168.1.4 12 net block &
pid[1]=$!

trap "kill ${pid[0]} ${pid[1]}; exit 1" INT

make CC=/usr/bin/gcc -j16 x86 lib_x86 lib lib_lib kernel init

wait ${pid[0]} ${pid[1]}

make CC=/usr/bin/gcc -j16
