#!/bin/bash

CC=/usr/bin/gcc

remote_build ()
{
	ip=$1

	rsync --delete --exclude=".git" --exclude="G*" -a . $ip::linux
	ssh $ip "cd /dev/shm/linux; make CC=$CC -j$2 "${@:3}" && find build | cpio -o > $ip.cpio 2> /dev/null"
	rsync $ip::linux/$ip.cpio .
	cpio -id < $ip.cpio
	rm $ip.cpio
}

make clean

remote_build 192.168.1.2 12 fs mm drivers block init 2> /dev/null &
pid[0]=$!

trap "kill ${pid[0]}; exit 1" INT

make CC=$CC -j16 x86 lib kernel net init security
wait ${pid[0]}

make CC=$CC -j16
