obj-y += virtio.o virtio_ring.o
obj-y += virtio_pci_modern_dev.o
obj-y += virtio_pci_legacy_dev.o
obj-y += virtio_pci.o
virtio_pci-y := virtio_pci_modern.o virtio_pci_common.o
virtio_pci-y += virtio_pci_legacy.o
