# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux network device drivers.
#

#
# Networking Core Drivers
obj-$(CONFIG_NET) += loopback.o
obj-$(CONFIG_VIRTIO_NET) += virtio_net.o
obj-$(CONFIG_NET_FAILOVER) += net_failover.o
