obj-y			:= component.o core.o bus.o dd.o syscore.o \
			   driver.o class.o platform.o \
			   cpu.o firmware.o init.o map.o devres.o \
			   attribute_container.o transport_class.o \
			   topology.o container.o property.o cacheinfo.o \
			   swnode.o
obj-y	+= devtmpfs.o
obj-y			+= power/
obj-y				+= firmware_loader/
CFLAGS_trace.o		:= -I$(src)
