# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux unix domain socket layer.
#

obj-y	+= unix.o

unix-y			:= af_unix.o garbage.o
unix-y	+= sysctl_net_unix.o

unix_diag-y		:= diag.o

obj-y	+= scm.o
