obj-y = fork.o exec_domain.o panic.o cpu.o exit.o softirq.o resource.o sysctl.o capability.o ptrace.o user.o signal.o sys.o umh.o workqueue.o pid.o task_work.o extable.o params.o kthread.o sys_ni.o nsproxy.o notifier.o ksysfs.o cred.o reboot.o async.o range.o smpboot.o ucount.o regset.o groups.o irq_work.o power/qos.o bpf/core.o static_call.o static_call_inline.o context_tracking.o iomem.o up.o platform-feature.o \
	$(addprefix sched/, core.o fair.o build_policy.o build_utility.o) \
	$(addprefix locking/, mutex.o semaphore.o rwsem.o percpu-rwsem.o rtmutex_api.o) \
	$(addprefix printk/, printk.o printk_safe.o printk_ringbuffer.o) \
	$(addprefix irq/, irqdesc.o handle.o manage.o spurious.o resend.o chip.o dummychip.o devres.o autoprobe.o irqdomain.o proc.o matrix.o msi.o) \
	$(addprefix rcu/, update.o sync.o srcutiny.o tiny.o) \
	$(addprefix dma/, mapping.o direct.o swiotlb.o remap.o) \
	$(addprefix entry/, common.o syscall_user_dispatch.o) \
	$(addprefix time/, time.o timer.o hrtimer.o timekeeping.o ntp.o clocksource.o jiffies.o timer_list.o timeconv.o timecounter.o alarmtimer.o posix-timers.o posix-cpu-timers.o posix-clock.o itimer.o clockevents.o tick-common.o tick-broadcast.o tick-oneshot.o tick-sched.o vsyscall.o) \
	$(addprefix futex/, core.o syscalls.o pi.o requeue.o waitwake.o) \
	$(addprefix events/, core.o ring_buffer.o callchain.o hw_breakpoint.o)
