obj-y     = fork.o exec_domain.o panic.o 	    cpu.o exit.o softirq.o resource.o 	    sysctl.o capability.o ptrace.o user.o 	    signal.o sys.o umh.o workqueue.o pid.o task_work.o 	    extable.o params.o 	    kthread.o sys_ni.o nsproxy.o 	    notifier.o ksysfs.o cred.o reboot.o 	    async.o range.o smpboot.o ucount.o regset.o groups.o

obj-y += sched/
obj-y += locking/
obj-y += power/
obj-y += printk/
obj-y += irq/
obj-y += rcu/
obj-y += dma/
obj-y += entry/
obj-y += stacktrace.o
obj-y += time/
obj-y += futex/
obj-y += dma.o
obj-y += smp.o
obj-y += kallsyms.o
obj-y += stop_machine.o
obj-y += utsname_sysctl.o
obj-y += irq_work.o
obj-y += bpf/
obj-y += static_call.o
obj-y += static_call_inline.o
obj-y += events/
obj-y += context_tracking.o

obj-y += iomem.o
obj-y += rseq.o
