obj-y := irqdesc.o handle.o manage.o spurious.o resend.o chip.o dummychip.o devres.o
obj-y += autoprobe.o
obj-y += irqdomain.o
obj-y += proc.o
obj-y += migration.o
obj-y += cpuhotplug.o
obj-y += affinity.o
obj-y += matrix.o
