# SPDX-License-Identifier: GPL-2.0
obj-y		+= core.o
obj-$(CONFIG_PERF_EVENTS_AMD_BRS)	+= brs.o
obj-$(CONFIG_PERF_EVENTS_AMD_POWER)	+= power.o
obj-$(CONFIG_X86_LOCAL_APIC)		+= ibs.o
obj-$(CONFIG_PERF_EVENTS_AMD_UNCORE)	+= amd-uncore.o
amd-uncore-objs				:= uncore.o
