obj-y				+= pci/

obj-y				+= video/
obj-y				+= rtc/
obj-y				+= input/

obj-y				+= virtio/

obj-y				+= tty/
obj-y				+= char/

obj-$(CONFIG_FB_I810)           += video/fbdev/i810/
obj-$(CONFIG_FB_INTEL)          += video/fbdev/intelfb/

obj-y				+= base/ block/
obj-y				+= net/
obj-y				+= firmware/
obj-y				+= clocksource/
obj-y				+= platform/
