obj-y += time.o timer.o hrtimer.o
obj-y += timekeeping.o ntp.o clocksource.o jiffies.o timer_list.o
obj-y += timeconv.o timecounter.o alarmtimer.o
obj-y += posix-timers.o posix-cpu-timers.o posix-clock.o itimer.o
obj-y += clockevents.o tick-common.o
obj-y += tick-broadcast.o
obj-y += tick-oneshot.o tick-sched.o
obj-y += vsyscall.o
