vmlinux.o: $(KBUILD_VMLINUX_OBJS) $(KBUILD_VMLINUX_LIBS)
	$(Q) $(LD) -m elf_x86_64 -r -o $@ $(addprefix -T , $(initcalls-lds)) \
	--whole-archive $(KBUILD_VMLINUX_OBJS) --no-whole-archive \
	--start-group $(KBUILD_VMLINUX_LIBS) --end-group

targets += vmlinux.o
