PHONY := all
all:

src := $(subst /generated,,$(obj))

-include $(src)/Kbuild

include $(srctree)/$(generic)/Kbuild

mandatory-y := $(filter-out $(generated-y), $(mandatory-y))
generic-y   := $(foreach f, $(mandatory-y), $(if $(wildcard $(srctree)/$(src)/$(f)),,$(f)))

generic-y   := $(addprefix build/$(obj)/, $(generic-y))

cmd_wrap = echo "\#include <asm-generic/$*.h>" > $@

all: $(generic-y)

build/$(obj)/%.h:
	@ $(cmd_wrap)

.PHONY: $(PHONY)
