obj-y						+= chacha.o

libaes-y					:= aes.o

libarc4-y					:= arc4.o

obj-y						+= libblake2s.o
libblake2s-y					:= blake2s.o
libblake2s-y	+= blake2s-generic.o

libchacha20poly1305-y				+= chacha20poly1305.o

libcurve25519-generic-y				:= curve25519-fiat32.o
libcurve25519-generic-y	:= curve25519-hacl64.o
libcurve25519-generic-y				+= curve25519-generic.o

libcurve25519-y					+= curve25519.o

libdes-y					:= des.o

libpoly1305-y					:= poly1305-donna32.o
libpoly1305-y	:= poly1305-donna64.o
libpoly1305-y					+= poly1305.o

libsha256-y					:= sha256.o
libblake2s-y                                   += blake2s-selftest.o
