obj-y := devres.o socket.o ipv6/addrconf_core.o ethernet/eth.o \
	$(addprefix ethtool/, ioctl.o common.o) \
	$(addprefix sched/, sch_generic.o sch_mq.o) \
	$(addprefix unix/, af_unix.o garbage.o scm.o) \
	$(addprefix netlink/, af_netlink.o genetlink.o policy.o) \
	$(addprefix core/, sock.o request_sock.o skbuff.o datagram.o stream.o scm.o gen_stats.o gen_estimator.o net_namespace.o secure_seq.o flow_dissector.o dev.o dev_addr_lists.o dst.o netevent.o neighbour.o rtnetlink.o utils.o link_watch.o filter.o sock_diag.o dev_ioctl.o tso.o sock_reuseport.o fib_notifier.o xdp.o flow_offload.o gro.o net-sysfs.o net-procfs.o)
